title: Osvaldo Ruiz - Aspiring Data Analyst
email: oruiz.code@gmail.com
description: >-
  Aspiring Data Analyst with expertise in Python, SQL, and statistical analysis.
  Passionate about turning data into actionable insights.

  B.S In Information System from Arizona State University

baseurl: ""
url: "https://ruizosvaldo.github.io/ruizosvaldo"

github_username: ruizosvaldo
linkedin_username: https://www.linkedin.com/in/osvaldoruiz/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Resume
    url: /resume/
  - title: Resume
    url: /resume/
