title: Osvaldo Ruiz
email: oruiz.code@gmail.com
description: >-
                Aspiring Data Analyst looking to use my skills in transforming data into actionable items.

baseurl: ""
url: "https://ruizosvaldo.github.io"

github_username: ruizosvaldo
linkedin_username: osvaldoruiz
twitter_username: ORuizCode

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Resume
    url: /resume/
